#ifndef ERS_API_FUNCTIONS_DEFINITION
#define ERS_API_FUNCTIONS_DEFINITION

#define ERS_API_FUNCTION_HEADER_MAJOR_VERSION 0
#define ERS_API_FUNCTION_HEADER_MINOR_VERSION 0

#include <stddef.h>
#include <stdio.h>
#include <stdint.h>

#if defined _WIN32
    #define ERS_IMPORT extern "C" __declspec(dllimport)
#else
    #define ERS_IMPORT extern "C" __attribute__((__visibility__("default")))
#endif

// Temporary typedef until we found a good place for shared information.
typedef uint64_t EntityID; typedef uint64_t SimulationTime;

namespace Ers::Engine
{
    ERS_IMPORT void* ERS_Debugger_Create(void* modelContainerPtr);
    ERS_IMPORT void* ERS_Debugger_Create_Window(void* modelContainerPtr, void* windowPtr);
    ERS_IMPORT void ERS_Debugger_Destroy(void* ptr);
    ERS_IMPORT void ERS_Debugger_BeginUpdate(void* ptr);
    ERS_IMPORT void ERS_Debugger_EndUpdate(void* ptr);
    ERS_IMPORT void* ERS_Debugger_GetWindow(void* ptr);
    ERS_IMPORT bool ERS_Debugger_Get_IsRunning(void* ptr);
    ERS_IMPORT void ERS_Debugger_Set_IsRunning(void* ptr, bool value);
    ERS_IMPORT void* ERS_Debugger_GetRenderContext(void* ptr);
    ERS_IMPORT bool ERS_Debugger_Is3DMode(void* ptr);
    ERS_IMPORT void* ERS_Debugger_GetSelectedSimulator(void* ptr);
    ERS_IMPORT EntityID ERS_Debugger_GetSelectedEntity(void* ptr);
    ERS_IMPORT uint32_t ERS_Debugger_Get_TopBarDockID(void* ptr);
    ERS_IMPORT uint32_t ERS_Debugger_Get_MainDockID(void* ptr);
    ERS_IMPORT uint32_t ERS_Debugger_Get_LeftSidebarDockID(void* ptr);
    ERS_IMPORT uint32_t ERS_Debugger_Get_CenterDockID(void* ptr);
    ERS_IMPORT uint32_t ERS_Debugger_Get_RightSidebarDockID(void* ptr);
    ERS_IMPORT uint32_t ERS_Debugger_Get_CenterMainDockID(void* ptr);
    ERS_IMPORT uint32_t ERS_Debugger_Get_CenterBottomDockID(void* ptr);
    ERS_IMPORT void ERS_RunWithProgressBar();
    ERS_IMPORT void ERS_SetBindingType(const char* bindingType);
    ERS_IMPORT void ERS_License_ForceOnlineFetch();
    ERS_IMPORT void ERS_Initialize();
    ERS_IMPORT void ERS_Uninitialize();
    ERS_IMPORT uint32_t ERS_GetMajorVersion();
    ERS_IMPORT uint32_t ERS_GetMinorVersion();
    ERS_IMPORT uint32_t ERS_GetPatchVersion();
    ERS_IMPORT bool ERS_IsDebugBuild();
    ERS_IMPORT bool ERS_License_Check();
    ERS_IMPORT void ERS_License_Activate(int licenseType);
    ERS_IMPORT void ERS_License_Deactivate();
    ERS_IMPORT uint32_t ERS_License_Info_DaysRemaining();
    ERS_IMPORT int ERS_License_Info_LicenseType();
    ERS_IMPORT bool ERS_License_HasFeature(const char* featureCode);
    ERS_IMPORT int ERS_License_GetLimits_MaxJobSystemCores();
    ERS_IMPORT int ERS_License_GetLimits_MaxComponentTypes();
    ERS_IMPORT char* ERS_License_EditionName();
    ERS_IMPORT void ERS_Logger_Trace(const char* message);
    ERS_IMPORT void ERS_Logger_Debug(const char* message);
    ERS_IMPORT void ERS_Logger_Warning(const char* message);
    ERS_IMPORT void ERS_Logger_Info(const char* message);
    ERS_IMPORT void ERS_Logger_Error(const char* message);
    ERS_IMPORT void ERS_Logger_Critical(const char* message);
    ERS_IMPORT void ERS_Logger_SetLogLevel(int logLevel);
    ERS_IMPORT void ERS_Logger_AddCallback(void(*logCallback)(int level, const char* message, void* callbackData), void* callbackData);
    ERS_IMPORT char* ERS_Settings_GetSetting(const char* section, const char* message, const char* defaultValue);
    ERS_IMPORT void ERS_Settings_SetSetting(const char* section, const char* message, const char* value);
    ERS_IMPORT void ERS_Settings_Clear();
    ERS_IMPORT bool ERS_VirtualFileSystem_MountDirectory(const char* path, const char* directoryName);
    ERS_IMPORT bool ERS_Serializer_IsWriting(void* serializerHandle);
    ERS_IMPORT void ERS_Serializer_SerializeUInt64(void* serializerHandle, const char* key, uint64_t* value);
    ERS_IMPORT void ERS_Serializer_SerializeInt64(void* serializerHandle, const char* key, int64_t* value);
    ERS_IMPORT void ERS_Serializer_SerializeUInt32(void* serializerHandle, const char* key, uint32_t* value);
    ERS_IMPORT void ERS_Serializer_SerializeInt32(void* serializerHandle, const char* key, int32_t* value);
    ERS_IMPORT void ERS_Serializer_SerializeDouble(void* serializerHandle, const char* key, double* value);
    ERS_IMPORT void ERS_Serializer_SerializeBool(void* serializerHandle, const char* key, bool* value);
    ERS_IMPORT void ERS_Serializer_SerializeFloat(void* serializerHandle, const char* key, float* value);
    ERS_IMPORT void ERS_Serializer_SerializeString(void* serializerHandle, const char* key, char** value, int* length);
    ERS_IMPORT void ERS_Serializer_PushObject(void* serializerHandle, const char* key);
    ERS_IMPORT void ERS_Serializer_PopObject(void* serializerHandle);
    ERS_IMPORT void ERS_Serializer_SetObject(void* serializerHandle, int index);
    ERS_IMPORT void ERS_Serializer_PushArray(void* serializerHandle, const char* key, int* size);
    ERS_IMPORT void ERS_Serializer_PopArray(void* serializerHandle);
    ERS_IMPORT int ERS_Serializer_GetArraySize(void* serializerHandle);
    ERS_IMPORT void ERS_Serializer_SaveToFolder(void* modelContainerInstance, const char* folderPath);
    ERS_IMPORT void* ERS_Serializer_LoadFromFolder(const char* folderPath);
    ERS_IMPORT void ERS_Serializer_SaveToArchive(void* modelContainerInstance, const char* archivePath, int compressionLevel);
    ERS_IMPORT void* ERS_Serializer_LoadFromArchive(const char* archivePath, bool useCache);
    ERS_IMPORT void ERS_Serializer_ClearArchiveCache(const char* archivePath);
    ERS_IMPORT void ERS_Serializer_SerializeValueUInt64(void* serializerHandle, size_t index, uint64_t* value);
    ERS_IMPORT void ERS_Serializer_SerializeValueInt64(void* serializerHandle, size_t index, int64_t* value);
    ERS_IMPORT void ERS_Serializer_SerializeValueUInt32(void* serializerHandle, size_t index, uint32_t* value);
    ERS_IMPORT void ERS_Serializer_SerializeValueInt32(void* serializerHandle, size_t index, int32_t* value);
    ERS_IMPORT void ERS_Serializer_SerializeValueDouble(void* serializerHandle, size_t index, double* value);
    ERS_IMPORT void ERS_Serializer_SerializeValueBool(void* serializerHandle, size_t index, bool* value);
    ERS_IMPORT void ERS_Serializer_SerializeValueFloat(void* serializerHandle, size_t index, float* value);
    ERS_IMPORT void ERS_Serializer_SerializeValueString(void* serializerHandle, size_t index, char** value, int* length);
    ERS_IMPORT void ERS_Serializer_PushArrayElement(void* serializerHandle, size_t index, int* size);
    ERS_IMPORT void ERS_Serializer_PushObjectElement(void* serializerHandle, size_t index);
    ERS_IMPORT int ERS_PathSegment_GetType(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetFromX(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetFromY(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetFromZ(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetToX(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetToY(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetToZ(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetCenterX(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetCenterY(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetCenterZ(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetRadius(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetBeginAngle(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetEndAngle(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetEndZ(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP0X(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP0Y(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP0Z(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP1X(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP1Y(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP1Z(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP2X(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP2Y(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP2Z(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP3X(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP3Y(void* instance);
    ERS_IMPORT float ERS_PathSegment_GetP3Z(void* instance);
    ERS_IMPORT void ERS_PathSegment_GetPointAlongPath(void* instance, float t, float* vec3out);
    ERS_IMPORT void ERS_PathSegment_GetRotationAlongPath(void* instance, float t, float* vec3out);
    ERS_IMPORT void ERS_Random_Generator_Set_Seed(void* generator, size_t seed);
    ERS_IMPORT double ERS_Random_Generator_Sample(void* generator);
    ERS_IMPORT void ERS_Random_Generator_Reset(void* generator);
    ERS_IMPORT int ERS_Random_Generator_GetType(void* generator);
    ERS_IMPORT void ERS_Profiler_StartSession();
    ERS_IMPORT void ERS_Profiler_PrintResults();
    ERS_IMPORT void ERS_String_Destroy(void* str);
    ERS_IMPORT void* ERS_ThreadLocal_GetSubModel();
    ERS_IMPORT void* ERS_ThreadLocal_GetSubModelOrNull();
    ERS_IMPORT bool ERS_ThreadLocal_InsideSubModel();
    ERS_IMPORT void ERS_ThreadLocal_EnterSubModel(void* submodel);
    ERS_IMPORT void ERS_ThreadLocal_ExitSubModel();
    ERS_IMPORT void* ERS_ThreadLocal_GetCurrentSyncEvent();
    ERS_IMPORT bool ERS_ThreadLocal_IsInsideSyncEvent();
    ERS_IMPORT int32_t ERS_ThreadLocal_GetSyncEventTarget();
    ERS_IMPORT int32_t ERS_ThreadLocal_GetSyncEventSender();
    ERS_IMPORT void* ERS_ModelContainer_Create();
    ERS_IMPORT void ERS_ModelContainer_Release(void* instance);
    ERS_IMPORT void ERS_ModelContainer_Increase(void* instance);
    ERS_IMPORT size_t ERS_ModelContainer_GetSimulatorsCount(const void* modelContainerInstance);
    ERS_IMPORT void* ERS_ModelContainer_GetSimulator(void* modelContainerInstance, int index);
    ERS_IMPORT void* ERS_ModelContainer_GetSimulatorById(void* modelContainerInstance, const int32_t simulatorId);
    ERS_IMPORT void* ERS_ModelContainer_AddSimulator(void* modelContainerInstance, const char* tag, const uint8_t simulatorType);
    ERS_IMPORT void ERS_ModelContainer_RemoveSimulator(void* modelContainerInstance, void* coreSimulator);
    ERS_IMPORT SimulationTime ERS_ModelContainer_CurrentTime(const void* modelContainerInstance);
    ERS_IMPORT void ERS_ModelContainer_Update_Blocking(void* modelContainerInstance, SimulationTime timeStep);
    ERS_IMPORT double ERS_ModelContainer_SimulationSpeedOverRealtime(void* modelContainerInstance);
    ERS_IMPORT void ERS_ModelContainer_SetModelPrecision(void* modelContainerInstance, uint64_t newPrecision);
    ERS_IMPORT uint64_t ERS_ModelContainer_GetModelPrecision(void* modelContainerInstance);
    ERS_IMPORT bool ERS_ModelContainer_IsStarted(const void* modelContainerInstance);
    ERS_IMPORT void ERS_ModelContainer_SetSeed(void* modelContainerInstance, size_t seed);
    ERS_IMPORT void ERS_ModelContainer_GenerateRandomSeed(void* modelContainerInstance);
    ERS_IMPORT size_t ERS_ModelContainer_Seed(void* modelContainerInstance);
    ERS_IMPORT void* ERS_ModelContainer_FindSimulatorById(void* modelContainerInstance, const int32_t id);
    ERS_IMPORT void* ERS_ModelContainer_FindSimulatorByTag(void* modelContainerInstance, const char* tag);
    ERS_IMPORT void ERS_ModelContainer_AddSimulatorDependency(void* modelContainerInstance, void* fromSharedPtr, void* toSimulatorSharedPtr);
    ERS_IMPORT void ERS_ModelContainer_RemoveSimulatorDependency(void* modelContainerInstance, void* fromSimulatorSharedPtr, void* toSimulatorSharedPtr);
    ERS_IMPORT void ERS_ModelContainer_Start(void* modelContainerInstance);
    ERS_IMPORT const char* ERS_ModelContainer_GetWorkingDir(void* modelContainerInstance);
    ERS_IMPORT void ERS_ModelContainer_SetWorkingDir(void* modelContainerInstance, const char* path);
    ERS_IMPORT void* ERS_ModelManager_GetModelManager();
    ERS_IMPORT void ERS_ModelManager_AddModelContainer(void* modelManager, void* modelContainer, uint64_t releaseTime);
    ERS_IMPORT void ERS_ModelManager_RemoveModelContainer(void* modelManager, void* modelContainer);
    ERS_IMPORT size_t ERS_ModelManager_CountModelContainers(const void* modelManager);
    ERS_IMPORT void* ERS_ModelManager_GetModelContainerAt(void* modelManager, const size_t index);
    ERS_IMPORT bool ERS_ModelManager_HasModelContainer(const void* modelManager, const void* modelContainer);
    ERS_IMPORT void ERS_ModelManager_Update(void* updateManager);
    ERS_IMPORT bool ERS_LibraryCollection_OpenLibrary(void* instance, const char* libraryPath);
    ERS_IMPORT bool ERS_LibraryCollection_IsLibraryOpen(const void* instance, const char* libraryPath);
    ERS_IMPORT void* ERS_LibraryCollection_GetFunctionFromLibrary(const void* instance, const char* libraryPath, const char* functionName);
    ERS_IMPORT void* ERS_LibraryCollection_GetLibraryHandle(const void* instance, const char* libraryPath);
    ERS_IMPORT void* ERS_PersistentEvent_Create();
    ERS_IMPORT void ERS_PersistentEvent_Release(void* ptr);
    ERS_IMPORT bool ERS_PersistentEvent_IsEmpty(void* ptr);
    ERS_IMPORT void* ERS_PersistentEvent_GetSimulator(void* ptr);
    ERS_IMPORT void* ERS_PersistentEvent_GetSimEvent(void* ptr);
    ERS_IMPORT uint64_t ERS_SimEvent_Get_Time(void* ptr);
    ERS_IMPORT uint32_t ERS_SimEvent_Get_Priority(void* ptr);
    ERS_IMPORT bool ERS_SimEvent_IsSyncEvent(void* ptr);
    ERS_IMPORT void* ERS_Simulator_GetLibraryCollection(void* instance);
    ERS_IMPORT void* ERS_Simulator_GetSubModel(void* instance);
    ERS_IMPORT bool ERS_Simulator_IsRunTogether(void* instance, int32_t otherSimulatorId);
    ERS_IMPORT bool ERS_Simulator_IsBiDirectional(void* instance, int32_t otherSimulatorId);
    ERS_IMPORT char* ERS_Simulator_GetName(const void* instance);
    ERS_IMPORT uint64_t ERS_Simulator_GetTimeStep(const void* instance);
    ERS_IMPORT void ERS_Simulator_SetTimeStep(void* instance, uint64_t newTimeStep);
    ERS_IMPORT int32_t ERS_Simulator_GetID(const void* instance);
    ERS_IMPORT uint8_t ERS_Simulator_GetSimulatorType(const void* instance);
    ERS_IMPORT void* ERS_Simulator_GetAttachedModelContainer(void* instance);
    ERS_IMPORT size_t ERS_Simulator_GetDependenciesAmount(const void* instance);
    ERS_IMPORT char* ERS_Simulator_GetDependencyName(const void* instance, size_t index);
    ERS_IMPORT void* ERS_Simulator_FindDependencyById(void* instance, int32_t simulatorId);
    ERS_IMPORT void* ERS_Simulator_FindDependencyByName(void* instance, const char* nameTag, int nameSize);
    ERS_IMPORT void* ERS_Simulator_FindOutgoingDependencyById(void* instance, int32_t id);
    ERS_IMPORT void* ERS_Simulator_FindOutgoingDependencyByName(void* instance, const char* nameTag, int nameSize);
    ERS_IMPORT SimulationTime ERS_Simulator_GetCurrentTime(const void* simulatorInstance);
    ERS_IMPORT uint32_t ERS_BoxComponent_TypeId();
    ERS_IMPORT float ERS_BoxComponent_Get_Min_X(void* instance);
    ERS_IMPORT float ERS_BoxComponent_Get_Min_Y(void* instance);
    ERS_IMPORT float ERS_BoxComponent_Get_Min_Z(void* instance);
    ERS_IMPORT float ERS_BoxComponent_Get_Max_X(void* instance);
    ERS_IMPORT float ERS_BoxComponent_Get_Max_Y(void* instance);
    ERS_IMPORT float ERS_BoxComponent_Get_Max_Z(void* instance);
    ERS_IMPORT void ERS_BoxComponent_Set_Min(void* instance, float minX, float minY, float minZ);
    ERS_IMPORT void ERS_BoxComponent_Set_Max(void* instance, float maxX, float maxY, float maxZ);
    ERS_IMPORT float ERS_BoxComponent_Get_Dimensions_X(void* instance);
    ERS_IMPORT float ERS_BoxComponent_Get_Dimensions_Y(void* instance);
    ERS_IMPORT float ERS_BoxComponent_Get_Dimensions_Z(void* instance);
    ERS_IMPORT void ERS_BoxComponent_Set_Dimensions(void* instance, float dimsX, float dimsY, float dimsZ);
    ERS_IMPORT bool ERS_BoxComponent_InCollision_Point2D(void* instance, float pointX, float pointY);
    ERS_IMPORT bool ERS_BoxComponent_InCollision_Ray(void* instance, float posX, float posY, float posZ, float dirX, float dirY, float dirZ);
    ERS_IMPORT uint32_t ERS_ChannelComponent_TypeId();
    ERS_IMPORT void ERS_ChannelComponent_RegisterType(void* submodelInstance);
    ERS_IMPORT int ERS_ChannelComponent_GetType(void* instance);
    ERS_IMPORT EntityID ERS_ChannelComponent_GetConnectedTo(void* instance);
    ERS_IMPORT bool ERS_ChannelComponent_IsOpen(void* instance);
    ERS_IMPORT bool ERS_ChannelComponent_IsOpenStatic(EntityID channel);
    ERS_IMPORT bool ERS_Channel_Send(EntityID channelFrom, EntityID child);
    ERS_IMPORT void ERS_Channel_Open(EntityID channel);
    ERS_IMPORT void ERS_Channel_Close(EntityID channel);
    ERS_IMPORT bool ERS_Channel_IsReady(EntityID channel);
    ERS_IMPORT void ERS_Channel_Connect(EntityID channelA, EntityID channelB);
    ERS_IMPORT void ERS_Channel_AddChannelComponent(EntityID channel, int type, EntityID resource);
    ERS_IMPORT uint32_t ERS_GlobalComponentRegistry_RegisterScriptBehavior(const char* name, void*(*CreateInstance)(void* handle), void* handle, void(*OnCreation)(void* scriptBehaviorInstance), void(*OnAwake)(void* scriptBehaviorInstance), void(*OnStart)(void* scriptBehaviorInstance), void(*OnUpdate)(void* scriptBehaviorInstance), void(*OnLateUpdate)(void* scriptBehaviorInstance), void(*OnDestroy)(void* scriptBehaviorInstance), void(*OnEntering)(void* scriptBehaviorInstance, EntityID child), void(*OnEntered)(void* scriptBehaviorInstance, EntityID child), void(*OnExiting)(void* scriptBehaviorInstance, EntityID child), void(*OnExited)(void* scriptBehaviorInstance, EntityID child), void(*OnInputChannelReady)(void* scriptBehaviorInstance, EntityID inputChannel), void(*OnOutputChannelReady)(void* scriptBehaviorInstance, EntityID outputChannel), void(*OnReceive)(void* scriptBehaviorInstance, EntityID inputChannel, EntityID child), void(*Serialization)(void* scriptBehaviorInstance, void* serializer), void(*OnSubModelMove)(void* scriptBehaviorInstance, EntityID newConnectedEntity));
    ERS_IMPORT uint32_t ERS_GlobalComponentRegistry_RegisterComponent(const char* name, size_t sz, void* typeInfoPtr, void* customSerialize);
    ERS_IMPORT bool ERS_GlobalComponentRegistry_IsRegistered(uint32_t componentID);
    ERS_IMPORT uint32_t ERS_NameComponent_TypeId();
    ERS_IMPORT const char* ERS_NameComponent_GetName(void* nameComponentPointer);
    ERS_IMPORT void ERS_NameComponent_SetName(void* nameComponentPointer, const char* newName, int newNameSize);
    ERS_IMPORT uint32_t ERS_OutlineComponent_TypeId();
    ERS_IMPORT float ERS_OutlineComponent_Get_Center_X(void* instance);
    ERS_IMPORT void ERS_OutlineComponent_Set_Center_X(void* instance, float x);
    ERS_IMPORT float ERS_OutlineComponent_Get_Center_Y(void* instance);
    ERS_IMPORT void ERS_OutlineComponent_Set_Center_Y(void* instance, float y);
    ERS_IMPORT float ERS_OutlineComponent_Get_Center_Z(void* instance);
    ERS_IMPORT void ERS_OutlineComponent_Set_Center_Z(void* instance, float z);
    ERS_IMPORT float ERS_OutlineComponent_Get_Dimensions_X(void* instance);
    ERS_IMPORT float ERS_OutlineComponent_Get_Dimensions_Y(void* instance);
    ERS_IMPORT float ERS_OutlineComponent_Get_Dimensions_Z(void* instance);
    ERS_IMPORT void ERS_OutlineComponent_Set_Dimensions(void* instance, float dimsX, float dimsY, float dimsZ);
    ERS_IMPORT uint32_t ERS_PathComponent_TypeId();
    ERS_IMPORT void* ERS_PathComponent_GetSegment(void* instance, int index);
    ERS_IMPORT int ERS_PathComponent_GetNumSegments(void* instance);
    ERS_IMPORT void ERS_PathComponent_AddStraight(void* instance, float fromX, float fromY, float fromZ, float toX, float toY, float toZ);
    ERS_IMPORT void ERS_PathComponent_AddHelical(void* instance, float centerX, float centerY, float centerZ, float radius, float beginAngle, float endAngle, float endZ);
    ERS_IMPORT void ERS_PathComponent_AddCubicBezier(void* instance, float p0X, float p0Y, float p0Z, float p1X, float p1Y, float p1Z, float p2X, float p2Y, float p2Z, float p3X, float p3Y, float p3Z);
    ERS_IMPORT void ERS_PathComponent_AddCubicBezierFromDirections(void* instance, float startX, float startY, float startZ, float startDirX, float startDirY, float startDirZ, float endX, float endY, float endZ, float endDirX, float endDirY, float endDirZ, float curvature);
    ERS_IMPORT uint32_t ERS_RelationComponent_TypeId();
    ERS_IMPORT void ERS_RelationComponent_RegisterType(void* submodelInstance);
    ERS_IMPORT EntityID ERS_RelationComponent_GetParent(void* relationComponent);
    ERS_IMPORT EntityID ERS_RelationComponent_GetFirst(void* relationComponent);
    ERS_IMPORT EntityID ERS_RelationComponent_GetLast(void* relationComponent);
    ERS_IMPORT EntityID ERS_RelationComponent_GetPrevious(void* relationComponent);
    ERS_IMPORT EntityID ERS_RelationComponent_GetNext(void* relationComponent);
    ERS_IMPORT uint32_t ERS_RelationComponent_GetChildCount(void* relationComponent);
    ERS_IMPORT uint32_t ERS_RenderComponent_TypeId();
    ERS_IMPORT uint8_t ERS_RenderComponent_GetShape(void* instance);
    ERS_IMPORT void ERS_RenderComponent_SetShape(void* instance, uint8_t shape);
    ERS_IMPORT uint32_t ERS_RenderComponent_GetColor(void* instance);
    ERS_IMPORT void ERS_RenderComponent_SetColor(void* instance, uint32_t color);
    ERS_IMPORT void* ERS_RenderComponent_GetTexture2D(void* instance);
    ERS_IMPORT void ERS_RenderComponent_SetTexture2D(void* instance, void* texturePtr);
    ERS_IMPORT void ERS_RenderComponent_RemoveTexture2D(void* instance);
    ERS_IMPORT void ERS_RenderComponent_SetInstancedModel(void* instance, void* instancedModel);
    ERS_IMPORT void* ERS_RenderComponent_GetInstancedModel(void* instance);
    ERS_IMPORT uint32_t ERS_ResourceComponent_TypeId();
    ERS_IMPORT void ERS_ResourceComponent_RegisterType(void* submodelInstance);
    ERS_IMPORT size_t ERS_ResourceComponent_GetNumInputChannels(void* instance);
    ERS_IMPORT size_t ERS_ResourceComponent_GetNumOutputChannels(void* instance);
    ERS_IMPORT EntityID ERS_ResourceComponent_GetInputChannel(void* instance, size_t index);
    ERS_IMPORT EntityID ERS_ResourceComponent_GetOutputChannel(void* instance, size_t index);
    ERS_IMPORT void ERS_ResourceComponent_CloseAllInput(void* instance);
    ERS_IMPORT void ERS_ResourceComponent_OpenAllInput(void* instance);
    ERS_IMPORT void ERS_ResourceComponent_CloseAllOutput(void* instance);
    ERS_IMPORT void ERS_ResourceComponent_OpenAllOutput(void* instance);
    ERS_IMPORT uint32_t ERS_TransformComponent_TypeId();
    ERS_IMPORT void ERS_TransformComponent_RegisterType(void* submodelInstance);
    ERS_IMPORT float ERS_TransformComponent_Position_X(void* instance);
    ERS_IMPORT void ERS_TransformComponent_SetPosition_X(void* instance, float x);
    ERS_IMPORT float ERS_TransformComponent_Position_Y(void* instance);
    ERS_IMPORT void ERS_TransformComponent_SetPosition_Y(void* instance, float y);
    ERS_IMPORT float ERS_TransformComponent_Position_Z(void* instance);
    ERS_IMPORT void ERS_TransformComponent_SetPosition_Z(void* instance, float z);
    ERS_IMPORT void ERS_TransformComponent_SetPosition(void* instance, float x, float y, float z);
    ERS_IMPORT float ERS_TransformComponent_Scale_X(void* instance);
    ERS_IMPORT void ERS_TransformComponent_SetScale_X(void* instance, float x);
    ERS_IMPORT float ERS_TransformComponent_Scale_Y(void* instance);
    ERS_IMPORT void ERS_TransformComponent_SetScale_Y(void* instance, float y);
    ERS_IMPORT float ERS_TransformComponent_Scale_Z(void* instance);
    ERS_IMPORT void ERS_TransformComponent_SetScale_Z(void* instance, float z);
    ERS_IMPORT void ERS_TransformComponent_SetScale(void* instance, float x, float y, float z);
    ERS_IMPORT float ERS_TransformComponent_Rotation_X(void* instance);
    ERS_IMPORT void ERS_TransformComponent_SetRotation_X(void* instance, float x);
    ERS_IMPORT float ERS_TransformComponent_Rotation_Y(void* instance);
    ERS_IMPORT void ERS_TransformComponent_SetRotation_Y(void* instance, float y);
    ERS_IMPORT float ERS_TransformComponent_Rotation_Z(void* instance);
    ERS_IMPORT void ERS_TransformComponent_SetRotation_Z(void* instance, float z);
    ERS_IMPORT void ERS_TransformComponent_Rotate_X(void* instance, float angle);
    ERS_IMPORT void ERS_TransformComponent_Rotate_Y(void* instance, float angle);
    ERS_IMPORT void ERS_TransformComponent_Rotate_Z(void* instance, float angle);
    ERS_IMPORT void ERS_TransformComponent_SetRotationEuler(void* instance, float x, float y, float z);
    ERS_IMPORT void ERS_TransformComponent_SetQuaternion(void* instance, float x, float y, float z, float w);
    ERS_IMPORT float ERS_TransformComponent_GlobalPosition_X(const void* instance);
    ERS_IMPORT float ERS_TransformComponent_GlobalPosition_Y(const void* instance);
    ERS_IMPORT float ERS_TransformComponent_GlobalPosition_Z(const void* instance);
    ERS_IMPORT float ERS_TransformComponent_GlobalScale_X(const void* instance);
    ERS_IMPORT float ERS_TransformComponent_GlobalScale_Y(const void* instance);
    ERS_IMPORT float ERS_TransformComponent_GlobalScale_Z(const void* instance);
    ERS_IMPORT float ERS_TransformComponent_GlobalRotation_X(const void* instance);
    ERS_IMPORT float ERS_TransformComponent_GlobalRotation_Y(const void* instance);
    ERS_IMPORT float ERS_TransformComponent_GlobalRotation_Z(const void* instance);
    ERS_IMPORT EntityID ERS_Entity_Invalid();
    ERS_IMPORT EntityID ERS_Entity_GetParent(EntityID currentEntity);
    ERS_IMPORT uint64_t ERS_Entity_GetChildCount(EntityID currentEntity);
    ERS_IMPORT EntityID ERS_Entity_GetFirstChild(EntityID currentEntity);
    ERS_IMPORT EntityID ERS_Entity_GetLastChild(EntityID currentEntity);
    ERS_IMPORT EntityID ERS_Entity_GetPreviousSibling(EntityID currentEntity);
    ERS_IMPORT EntityID ERS_Entity_GetNextSibling(EntityID currentEntity);
    ERS_IMPORT bool ERS_Entity_IsValid(EntityID currentEntity);
    ERS_IMPORT void* ERS_EventScheduler_RegisterLocalEventType(uint64_t typeIdentifier, void(*callback)(void* data), void(*destructor)(void* data), void(*serialize)(void* data, void* serializerHandle), void*(*allocator)(), const char* uniqueName, const char* sourceLibrary, size_t size, const char* filePath, int lineNumber);
    ERS_IMPORT void* ERS_EventScheduler_RegisterSyncEventType(uint64_t eventTypeIdentifier, void(*onSenderSideCallback)(), void(*onTargetSideCallback)(), void(*serializeData)(void* dataContext, void* serializerHandle), uint32_t dataBlockSize, const char* name, const char* sourceLibrary, const char* filePath, int lineNumber);
    ERS_IMPORT uint64_t ERS_EventScheduler_ScheduleLocalEvent(int priority, uint64_t delay, void* dataPtr, void* eventTypeInfo);
    ERS_IMPORT void ERS_EventScheduler_CancelEvent(uint64_t eventKey);
    ERS_IMPORT void ERS_EventScheduler_SetPromise(uint64_t promise, int32_t outgoingDependencyID);
    ERS_IMPORT void* ERS_EventScheduler_LastScheduledSyncEvent();
    ERS_IMPORT uint64_t ERS_EventScheduler_GetPromise(int32_t outgoingDependencyID);
    ERS_IMPORT void* ERS_EventScheduler_ScheduleSyncEvent(uint64_t delay, int32_t targetSimulatorId, void* syncEventTypeInfo);
    ERS_IMPORT uint32_t ERS_EventScheduler_ExchangeSyncEventForEventID(void* syncEvent);
    ERS_IMPORT void ERS_EventScheduler_DelayEvent(uint64_t key, uint64_t delayAmount);
    ERS_IMPORT void* ERS_EventScheduler_AllocLocalEvent(void* eventTypeInfo);
    ERS_IMPORT void ERS_EventScheduler_FreeLocalEvent(void* dataPtr, void* eventTypeInfo);
    ERS_IMPORT EntityID ERS_SubModel_Move_Entity_To(void* targetSubModel, void* sourceSubModel, EntityID sourceEntity);
    ERS_IMPORT EntityID ERS_SubModel_Entity_Create_Name_Parent(void* submodel, const char* entityName, EntityID parent);
    ERS_IMPORT EntityID ERS_SubModel_Entity_Create(void* subModelPtr);
    ERS_IMPORT EntityID ERS_SubModel_Entity_Create_Name(void* subModelHandle, const char* entityName);
    ERS_IMPORT EntityID ERS_SubModel_FindEntity(void* submodelInstance, const char* entityName);
    ERS_IMPORT EntityID ERS_SubModel_FindEntity_Parent(void* subModelInstance, const char* entityName, EntityID root);
    ERS_IMPORT bool ERS_SubModel_Entity_Destroy(void* subModel, EntityID entity);
    ERS_IMPORT bool ERS_SubModel_Entity_Exists(const void* submodel, EntityID entityId);
    ERS_IMPORT void ERS_SubModel_Entity_Relation_Update_Parent(void* subModelHandle, EntityID entityId, EntityID parentId);
    ERS_IMPORT void ERS_SubModel_AddScriptBehavior(void* subModelHandle, EntityID entityID, uint32_t componentID, void* managedHandle);
    ERS_IMPORT void* ERS_SubModel_GetScriptBehavior(void* subModelHandle, EntityID entityID, uint32_t componentID);
    ERS_IMPORT void* ERS_SubModel_RemoveScriptBehavior(void* subModelHandle, EntityID entity, uint32_t componentID);
    ERS_IMPORT void* ERS_SubModel_GetComponent(void* subModelHandle, EntityID entity, uint32_t componentID);
    ERS_IMPORT void* ERS_SubModel_AddDataComponent(void* subModelHandle, EntityID entity, uint32_t componentID);
    ERS_IMPORT void* ERS_SubModel_GetSimulator(void* subModelHandle);
    ERS_IMPORT void ERS_SubModel_RemoveDataComponent(void* subModelHandle, EntityID entity, uint32_t componentID);
    ERS_IMPORT bool ERS_SubModel_HasComponent(const void* subModelHandle, EntityID entity, uint32_t componentID);
    ERS_IMPORT void* ERS_SubModel_GetRandomProperties(void* subModelHandle);
    ERS_IMPORT EntityID ERS_SubModel_SendEntityTo(void* subModelInstance, int32_t toSimulator, EntityID entity);
    ERS_IMPORT EntityID ERS_SubModel_ReceiveEntityFrom(void* subModelInstance, int32_t fromSimulator, EntityID pipeEntity);
    ERS_IMPORT EntityID ERS_SubModel_RootEntityID(const void* subModelHandle);
    ERS_IMPORT double ERS_SubModel_GenerateRandomDouble(void* subModelHandle, double min, double max);
    ERS_IMPORT uint64_t ERS_SubModel_GetModelPrecision(void* subModelInstance);
    ERS_IMPORT uint32_t ERS_SubModel_RegisterSubModelContext();
    ERS_IMPORT void ERS_SubModel_AddSubModelContext(void* subModelHandle, uint32_t SubModelContextTypeIdx, const char* name, void* SubModelContextPtr, void(*destructor)(void* contextHandle));
    ERS_IMPORT void* ERS_SubModel_GetContext(void* subModelHandle, uint32_t SubModelContextTypeIdx);
    ERS_IMPORT void* ERS_SubModelRandomProperties_Create();
    ERS_IMPORT void ERS_SubModelRandomProperties_Destroy(void* properties);
    ERS_IMPORT void ERS_SubModelRandomProperties_SetRandomGenerator_Type(void* submodel, int randomNumberGeneratorType);
    ERS_IMPORT void ERS_SubModelRandomProperties_SetRepetitive(void* submodel, bool value);
    ERS_IMPORT void ERS_SubModelRandomProperties_SetAntithetical(void* submodel, bool value);
    ERS_IMPORT void ERS_SubModelRandomProperties_SetSeed(void* submodel, size_t seed);
    ERS_IMPORT bool ERS_SubModelRandomProperties_IsRepetitive(void* submodel);
    ERS_IMPORT bool ERS_SubModelRandomProperties_IsAntithetical(void* submodel);
    ERS_IMPORT const size_t ERS_SubModelRandomProperties_GetOriginalSeed(const void* submodel);
    ERS_IMPORT void* ERS_SubModelRandomProperties_GetRandomNumberGenerator(void* submodel);
    ERS_IMPORT void* ERS_TypeInfo_RegisterStruct(const char* name);
    ERS_IMPORT void ERS_TypeInfo_AddField(void* componentTypeInfoPtr, const char* name, uint32_t fieldType, size_t offset, bool readOnly);
    ERS_IMPORT const char* ERS_TypeInfo_GetName(void* componentTypeInfoPtr);
    ERS_IMPORT void* ERS_Submodel_View_Create(void* subModelHandle, uint32_t* includedTypeIdArray_, uint32_t includedTypeArraySize, uint32_t* excludedTypeIdArray_, uint32_t excludedTypeArraySize);
    ERS_IMPORT bool ERS_Submodel_View_Next(void* viewHandle);
    ERS_IMPORT void* ERS_Submodel_View_GetComponent(void* viewHandle, size_t typeIndex);
    ERS_IMPORT void** ERS_Submodel_View_GetComponents(void* viewHandle);
    ERS_IMPORT EntityID ERS_Submodel_View_GetEntity(void* viewHandle);
    ERS_IMPORT void ERS_Submodel_View_Destroy(void* view);
    ERS_IMPORT uint32_t ERS_SyncEvent_GetSyncEventUID(void* syncEvent);
    ERS_IMPORT void* ERS_SyncEvent_GetData(void* syncEvent);
    ERS_IMPORT void ERS_CollisionSystem_UpdateBoundingBoxes(void* subModelInstance);
    ERS_IMPORT void ERS_PathAnimationSystem_Update(SimulationTime currentTime);
    ERS_IMPORT void ERS_PathAnimationSystem_Animate(EntityID toAnimate, SimulationTime startTime, SimulationTime endTime, float fromValue, float toValue, EntityID entityContainingPath, int pathIndex);
    ERS_IMPORT void ERS_PathAnimationSystem_AnimateStraightPath(EntityID toAnimate, SimulationTime startTime, SimulationTime endTime, float fromX, float fromY, float fromZ, float toX, float toY, float toZ);
    ERS_IMPORT void ERS_RenderSystem_Render2D(void* subModelInstance, void* renderContextInstance);
    ERS_IMPORT void ERS_RenderSystem_Render3D(void* subModelInstance, void* renderContextInstance);
    ERS_IMPORT void ERS_TransformSystem_UpdateGlobals(void* subModelInstance);
    ERS_IMPORT void ERS_ImGui_StyleColorsErsDark();
    ERS_IMPORT void ERS_ImGui_StyleColorsErsLight();
    ERS_IMPORT bool ERS_ImGui_SwitchButton(const char* label, bool* value, int flags);
    ERS_IMPORT bool ERS_ImGui_DragVectorXYZ(const char* label, float* x, float* y, float* z, int flags);
    ERS_IMPORT void* ERS_Window_Create();
    ERS_IMPORT void* ERS_Window_Create_Title(const char* title);
    ERS_IMPORT void ERS_Window_Destroy(void* ptr);
    ERS_IMPORT void ERS_Window_BeginFrame(void* ptr);
    ERS_IMPORT void ERS_Window_EndFrame(void* ptr);
    ERS_IMPORT bool ERS_Window_BeginRootDockSpace(void* ptr);
    ERS_IMPORT void ERS_Window_EndRootDockSpace(void* ptr);
    ERS_IMPORT uint32_t ERS_Window_GetRootDockSpaceID(void* ptr);
    ERS_IMPORT bool ERS_Window_Get_WantsClose(void* ptr);
    ERS_IMPORT void ERS_Window_Set_WantsClose(void* ptr, bool value);
    ERS_IMPORT void ERS_Window_SetWindowTitle(void* ptr, const char* title);
    ERS_IMPORT bool ERS_Window_SetWindowIcon(void* ptr, const char* path);
    ERS_IMPORT void ERS_EntityInspectorWidget_Window(void* simulatorPtr, EntityID entity, const char* name, bool* open, int flags);
    ERS_IMPORT void ERS_EntityInspectorWidget_Widget(void* simulatorPtr, EntityID entity);
    ERS_IMPORT void ERS_EntityInspectorWidget_EntityData(void* simulatorPtr, EntityID entity);
    ERS_IMPORT void ERS_EntityInspectorWidget_ComponentData(void* simulatorPtr, EntityID entity);
    ERS_IMPORT void ERS_EventInspectorWidget_Window(void* persistentEventPtr, const char* name, bool* open, int flags);
    ERS_IMPORT void ERS_EventInspectorWidget_Widget(void* persistentEventPtr);
    ERS_IMPORT void ERS_EventInspectorWidget_EventDetails(void* persistentEventPtr);
    ERS_IMPORT void ERS_EventInspectorWidget_SyncEventDetails(void* persistentEventPtr);
    ERS_IMPORT void ERS_EventInspectorWidget_LocalEventDetails(void* persistentEventPtr);
    ERS_IMPORT void* ERS_EventTimelineWidget_Create();
    ERS_IMPORT void ERS_EventTimeLineWidget_Destroy(void* ptr);
    ERS_IMPORT bool ERS_EventTimelineWidget_Window(void* ptr, void* modelContainerPtr, void* persistentEventPtr, bool isRunning, const char* name, bool* open, int flags);
    ERS_IMPORT bool ERS_EventTimelineWidget_Widget(void* ptr, void* modelContainerPtr, void* persistentEventPtr, bool isRunning);
    ERS_IMPORT bool ERS_EventTimelineWidget_Get_ShowLocalEvents(void* ptr);
    ERS_IMPORT void ERS_EventTimelineWidget_Set_ShowLocalEvents(void* ptr, bool value);
    ERS_IMPORT bool ERS_EventTimelineWidget_Get_ShowSyncEvents(void* ptr);
    ERS_IMPORT void ERS_EventTimelineWidget_Set_ShowSyncEvents(void* ptr, bool value);
    ERS_IMPORT bool ERS_EventTimelineWidget_Get_AutoScroll(void* ptr);
    ERS_IMPORT void ERS_EventTimelineWidget_Set_AutoScroll(void* ptr, bool value);
    ERS_IMPORT size_t ERS_EventTimelineWidget_Get_MaxEvents(void* ptr);
    ERS_IMPORT void ERS_EventTimelineWidget_Set_MaxEvents(void* ptr, size_t value);
    ERS_IMPORT void* ERS_InspectorWidget_Create();
    ERS_IMPORT void ERS_InspectorWidget_Destroy(void* ptr);
    ERS_IMPORT void ERS_InspectorWidget_Window(void* ptr, uint8_t selectedType, void* modelContainerPtr, void* simulatorPtr, void* entitySimulatorPtr, EntityID entity, void* persistentEventPtr, const char* name, bool* open, int flags);
    ERS_IMPORT void ERS_InspectorWidget_Widget(void* ptr, uint8_t selectedType, void* modelContainerPtr, void* simulatorPtr, void* entitySimulatorPtr, EntityID entity, void* persistentEventPtr);
    ERS_IMPORT void* ERS_LicensingWidget_Create();
    ERS_IMPORT void ERS_LicensingWidget_Destroy(void* ptr);
    ERS_IMPORT void ERS_LicensingWidget_Window(void* ptr, const char* name, bool* open, int flags);
    ERS_IMPORT void ERS_LicensingWidget_Widget(void* ptr);
    ERS_IMPORT void* ERS_LogWidget_Create();
    ERS_IMPORT void ERS_LogWidget_Destroy(void* ptr);
    ERS_IMPORT void ERS_LogWidget_Window(void* ptr, const char* name, bool* open, int flags);
    ERS_IMPORT void ERS_LogWidget_Widget(void* ptr);
    ERS_IMPORT int ERS_LogWidget_Get_SelectedLogLevel(void* ptr);
    ERS_IMPORT void ERS_LogWidget_Set_SelectedLogLevel(void* ptr, int logLevel);
    ERS_IMPORT bool ERS_LogWidget_Get_AutoScroll(void* ptr);
    ERS_IMPORT void ERS_LogWidget_Set_AutoScroll(void* ptr, bool autoScroll);
    ERS_IMPORT void ERS_ModelContainerInspectorWidget_Window(void* modelContainerPtr, const char* name, bool* open, int flags);
    ERS_IMPORT void ERS_ModelContainerInspectorWidget_Widget(void* modelContainerPtr);
    ERS_IMPORT void* ERS_ModelHierarchyWidget_Create();
    ERS_IMPORT void ERS_ModelHierarchyWidget_Destroy(void* ptr);
    ERS_IMPORT bool ERS_ModelHierarchyWidget_Window(void* ptr, void* modelContainerPtr, void** selectedSimulatorPtr, void** selectedEntitySimulatorPtr, EntityID* selectedEntity, uint8_t* selectedTypePtr, const char* name, bool* open, int flags);
    ERS_IMPORT bool ERS_ModelHierarchyWidget_Widget(void* modelContainerPtr, int treeNodeFlags, void** selectedSimulatorPtr, void** selectedEntitySimulatorPtr, EntityID* selectedEntity, uint8_t* selectedTypePtr);
    ERS_IMPORT void* ERS_ModelProgressionWidget_Create();
    ERS_IMPORT void ERS_ModelProgressionWidget_Destroy(void* ptr);
    ERS_IMPORT void* ERS_ModelProgressionWidget_Window(void* ptr, const void* modelContainerPtr, const char* name, bool* open, int flags);
    ERS_IMPORT void* ERS_ModelProgressionWidget_Widget(void* ptr, const void* modelContainerPtr);
    ERS_IMPORT void ERS_ModelProgressionWidget_Reset(void* ptr);
    ERS_IMPORT void* ERS_ModelStructureWidget_Create();
    ERS_IMPORT void ERS_ModelStructureWidget_Destroy(void* ptr);
    ERS_IMPORT void ERS_ModelStructureWidget_Window(void* ptr, void* modelContainerPtr, const char* name, bool* open, int flags);
    ERS_IMPORT void ERS_ModelStructureWidget_Widget(void* ptr, void* modelContainerPtr, int heatMapMode);
    ERS_IMPORT bool ERS_ModelStructureWidget_Get_ShowGrid(void* ptr);
    ERS_IMPORT void ERS_ModelStructureWidget_Set_ShowGrid(void* ptr, bool value);
    ERS_IMPORT int ERS_ModelStructureWidget_Get_SelectedHeatMapMode(void* ptr);
    ERS_IMPORT void ERS_ModelStructureWidget_Set_SelectedHeatMapMode(void* ptr, int value);
    ERS_IMPORT bool ERS_ModelStructureWidget_Get_ShowSimulatorGroups(void* ptr);
    ERS_IMPORT void ERS_ModelStructureWidget_Set_ShowSimulatorGroups(void* ptr, bool value);
    ERS_IMPORT bool ERS_ModelStructureWidget_Get_ShowSimulatorSuperGroups(void* ptr);
    ERS_IMPORT void ERS_ModelStructureWidget_Set_ShowSimulatorSuperGroups(void* ptr, bool value);
    ERS_IMPORT int ERS_ModelStructureWidget_Get_SelectedGroupStyle(void* ptr);
    ERS_IMPORT void ERS_ModelStructureWidget_Set_SelectedGroupStyle(void* ptr, int value);
    ERS_IMPORT void* ERS_RunControlsWidget_Create();
    ERS_IMPORT void ERS_RunControlsWidget_Destroy(void* ptr);
    ERS_IMPORT void ERS_RunControlsWidget_Window(void* ptr, void* modelContainerPtr, bool* isRunning, const char* name);
    ERS_IMPORT void ERS_RunControlsWidget_Widget(void* ptr, void* modelContainerPtr, bool* isRunning);
    ERS_IMPORT void* ERS_SimulatorInspectorWidget_Create();
    ERS_IMPORT void ERS_SimulatorInspectorWidget_Destroy(void* ptr);
    ERS_IMPORT void ERS_SimulatorInspectorWidget_Window(void* ptr, void* simulatorPtr, const char* name, bool* open, int flags);
    ERS_IMPORT void ERS_SimulatorInspectorWidget_Widget(void* ptr, void* simulatorPtr);
    ERS_IMPORT void* ERS_SpeedupWidget_Create();
    ERS_IMPORT void ERS_SpeedupWidget_Destroy(void* ptr);
    ERS_IMPORT void ERS_SpeedupWidget_Window(void* ptr, const char* name, bool* open, int flags);
    ERS_IMPORT void ERS_SpeedupWidget_Widget(void* ptr);
    ERS_IMPORT void ERS_SpeedupWidget_Update(void* ptr, const void* modelContainerPtr);
    ERS_IMPORT void* ERS_VisualizationWidget_Create();
    ERS_IMPORT void ERS_VisualizationWidget_Destroy(void* ptr);
    ERS_IMPORT void ERS_VisualizationWidget_Window(void* ptr, void* renderContextPtr, const char* name, bool* open, int flags);
    ERS_IMPORT void ERS_VisualizationWidget_Widget(void* ptr, void* renderContextPtr);
    ERS_IMPORT bool ERS_VisualizationWidget_Get_Is3DMode(void* ptr);
    ERS_IMPORT void ERS_VisualizationWidget_Set_Is3DMode(void* ptr, bool value);
    ERS_IMPORT void ERS_Camera2D_UpdateTransform(void* instance, int screenWidth, int screenHeight);
    ERS_IMPORT float ERS_Camera2D_GetPositionX(void* instance);
    ERS_IMPORT void ERS_Camera2D_SetPositionX(void* instance, float x);
    ERS_IMPORT float ERS_Camera2D_GetPositionY(void* instance);
    ERS_IMPORT void ERS_Camera2D_SetPositionY(void* instance, float y);
    ERS_IMPORT float ERS_Camera2D_GetZoom(void* instance);
    ERS_IMPORT void ERS_Camera2D_SetZoom(void* instance, float zoom);
    ERS_IMPORT float ERS_Camera2D_SizePerPixel(void* instance);
    ERS_IMPORT void ERS_Camera2D_GetWorldPos(void* instance, int screenWidth, int screenHeight, float screenPosX, float screenPosY, float* resultX, float* resultY);
    ERS_IMPORT void* ERS_Camera2DController_Create(void* camera2DPtr);
    ERS_IMPORT void ERS_Camera2DController_Destroy(void* corePtr);
    ERS_IMPORT void ERS_Camera2DController_ControlCamera(void* instance, int screenWidth, int screenHeight);
    ERS_IMPORT void ERS_Camera2DController_SetScreenSize(void* instance, int width, int height);
    ERS_IMPORT void ERS_Camera2DController_Update(void* instance, float mouseX, float mouseY);
    ERS_IMPORT void ERS_Camera2DController_StartDragging(void* instance, float mouseX, float mouseY);
    ERS_IMPORT void ERS_Camera2DController_StopDragging(void* instance);
    ERS_IMPORT void ERS_Camera2DController_Zoom(void* instance, float baseF, float power);
    ERS_IMPORT float ERS_Camera3D_GetPositionX(void* instance);
    ERS_IMPORT void ERS_Camera3D_SetPositionX(void* instance, float x);
    ERS_IMPORT float ERS_Camera3D_GetPositionY(void* instance);
    ERS_IMPORT void ERS_Camera3D_SetPositionY(void* instance, float y);
    ERS_IMPORT float ERS_Camera3D_GetPositionZ(void* instance);
    ERS_IMPORT void ERS_Camera3D_SetPositionZ(void* instance, float z);
    ERS_IMPORT float ERS_Camera3D_GetLookAtX(void* instance);
    ERS_IMPORT void ERS_Camera3D_SetLookAtX(void* instance, float x);
    ERS_IMPORT float ERS_Camera3D_GetLookAtY(void* instance);
    ERS_IMPORT void ERS_Camera3D_SetLookAtY(void* instance, float y);
    ERS_IMPORT float ERS_Camera3D_GetLookAtZ(void* instance);
    ERS_IMPORT void ERS_Camera3D_SetLookAtZ(void* instance, float z);
    ERS_IMPORT float ERS_Camera3D_GetFovInTurns(void* instance);
    ERS_IMPORT void ERS_Camera3D_SetFovInTurns(void* instance, float fov);
    ERS_IMPORT float ERS_Camera3D_GetZNear(void* instance);
    ERS_IMPORT void ERS_Camera3D_SetZNear(void* instance, float zNear);
    ERS_IMPORT float ERS_Camera3D_GetZFar(void* instance);
    ERS_IMPORT void ERS_Camera3D_SetZFar(void* instance, float zFar);
    ERS_IMPORT void ERS_Camera3D_SetLookAt(void* instance, float x, float y, float z);
    ERS_IMPORT void ERS_Camera3D_UpdateTransform(void* instance, int screenWidth, int screenHeight);
    ERS_IMPORT void ERS_Camera3D_GetPickRay(void* instance, int screenWidth, int screenHeight, int screenPosX, int screenPosY, float* outPosX, float* outPosY, float* outPosZ, float* outDirX, float* outDirY, float* outDirZ);
    ERS_IMPORT void* ERS_Camera3DController_Create(void* camera3DPtr);
    ERS_IMPORT void ERS_Camera3DController_Destroy(void* instance);
    ERS_IMPORT void ERS_Camera3DController_ControlCamera(void* instance, int screenWidth, int screenHeight, float deltaTime, float lookAtZ);
    ERS_IMPORT void ERS_Camera3DController_Update(void* instance, float deltaTime);
    ERS_IMPORT void ERS_Camera3DController_SwitchCameraMode(void* instance, int mode);
    ERS_IMPORT int ERS_Camera3DController_GetCameraMode(void* instance);
    ERS_IMPORT float ERS_Camera3DController_GetHeadBobbingIntensity(void* instance);
    ERS_IMPORT void ERS_Camera3DController_SetHeadBobbingIntensity(void* instance, float intensity);
    ERS_IMPORT void* ERS_InputHandler_GetAction(const char* name);
    ERS_IMPORT bool ERS_InputHandler_ExistsAction(const char* name);
    ERS_IMPORT void ERS_InputHandler_Cycle();
    ERS_IMPORT void ERS_InputHandler_UpdateMousePos(int x, int y);
    ERS_IMPORT bool ERS_InputAction_GetTriggered(void* instance);
    ERS_IMPORT void ERS_InputAction_SetTriggered(void* instance, bool triggered);
    ERS_IMPORT bool ERS_InputAction_GetReleased(void* instance);
    ERS_IMPORT void ERS_InputAction_SetReleased(void* instance, bool released);
    ERS_IMPORT float ERS_InputAction_GetStrength(void* instance);
    ERS_IMPORT void ERS_InputAction_SetStrength(void* instance, float strength);
    ERS_IMPORT void* ERS_InstancedModel_Create();
    ERS_IMPORT void ERS_InstancedModel_Destroy(void* instance);
    ERS_IMPORT void ERS_InstancedModel_PushInstance(void* instance, float posX, float posY, float posZ, float rotX, float rotY, float rotZ, float scaleX, float scaleY, float scaleZ);
    ERS_IMPORT void ERS_InstancedModel_SetMesh(void* instance, void* meshPtr);
    ERS_IMPORT void ERS_InstancedModel_Clear(void* instance);
    ERS_IMPORT void* ERS_Material_Copy_Shallow(void* instance);
    ERS_IMPORT uint32_t ERS_Material_GetDiffuseColor(void* instance);
    ERS_IMPORT void ERS_Material_SetDiffuseColor(void* instance, uint32_t color);
    ERS_IMPORT void* ERS_Mesh_Create();
    ERS_IMPORT void ERS_Mesh_Release(void* instance);
    ERS_IMPORT void ERS_Mesh_Increase(void* instance);
    ERS_IMPORT void ERS_Mesh_Destroy(void* instance);
    ERS_IMPORT void* ERS_Mesh_Material(void* instance);
    ERS_IMPORT void ERS_Mesh_SetDefaultMaterial(void* instance);
    ERS_IMPORT void ERS_Mesh_Clear(void* instance);
    ERS_IMPORT void ERS_Mesh_PushVertex3D(void* instance, float x, float y, float z, float nx, float ny, float nz, float u, float v, uint32_t color);
    ERS_IMPORT void ERS_Mesh_PushIndex(void* instance, uint32_t index);
    ERS_IMPORT void ERS_Mesh_PushTriangle(void* instance, float pos0X, float pos0Y, float pos0Z, float uv0X, float uv0Y, float pos1X, float pos1Y, float pos1Z, float uv1X, float uv1Y, float pos2X, float pos2Y, float pos2Z, float uv2X, float uv2Y, uint32_t color);
    ERS_IMPORT void ERS_Mesh_PushQuad(void* instance, float pos0X, float pos0Y, float pos0Z, float uv0X, float uv0Y, float pos1X, float pos1Y, float pos1Z, float uv1X, float uv1Y, float pos2X, float pos2Y, float pos2Z, float uv2X, float uv2Y, float pos3X, float pos3Y, float pos3Z, float uv3X, float uv3Y, uint32_t color, float normX, float normY, float normZ);
    ERS_IMPORT void ERS_Mesh_PushCube(void* instance, float posX, float posY, float posZ, float sizeX, float sizeY, float sizeZ, uint32_t color);
    ERS_IMPORT void ERS_Mesh_PushSphere(void* instance, float centerX, float centerY, float centerZ, uint8_t subdivisions, float radius, uint32_t color);
    ERS_IMPORT void ERS_Mesh_PushPyramid(void* instance, float centerX, float centerY, float centerZ, float dimsX, float dimsY, float dimsZ, uint32_t color);
    ERS_IMPORT void ERS_Mesh_PushBeam(void* instance, float fromX, float fromY, float fromZ, float toX, float toY, float toZ, float upX, float upY, float upZ, float width, float height, uint32_t color);
    ERS_IMPORT void ERS_Mesh_PushText3D(void* instance, void* fontInstance, const char* text, float posX, float posY, float posZ, float rightX, float rightY, float rightZ, float upX, float upY, float upZ, float scale, uint32_t color);
    ERS_IMPORT void ERS_Mesh_PushText3DAligned(void* instance, void* fontInstance, const char* text, float centerX, float centerY, float centerZ, float normalX, float normalY, float normalZ, float worldUpx, float worldUpy, float worldUpz, float scale, uint32_t color);
    ERS_IMPORT void ERS_Mesh_PushTextBillboard(void* instance, void* fontInstance, const char* text, float posX, float posY, float posZ, float cameraX, float cameraY, float cameraZ, float worldUpX, float worldUpY, float worldUpZ, float scale, uint32_t color);
    ERS_IMPORT void ERS_Mesh_PushText3DDefault(void* instance, const char* text, float posX, float posY, float posZ, float rightX, float rightY, float rightZ, float upX, float upY, float upZ, float scale, uint32_t color);
    ERS_IMPORT void ERS_Mesh_PushVerticalHelicalStrip(void* instance, float centerX, float centerY, float centerZ, float radius, float beginAngle, float endAngle, float endZ, float stripHeight, uint32_t color, int segments, bool normalsInward);
    ERS_IMPORT void ERS_Mesh_PushHorizontalHelicalStrip(void* instance, float centerX, float centerY, float centerZ, float radius, float beginAngle, float endAngle, float endZ, float stripLength, uint32_t color, int segments, bool normalUp);
    ERS_IMPORT void ERS_Mesh_PushHelicalBeam(void* instance, float centerX, float centerY, float centerZ, float radius, float beginAngle, float endAngle, float endZ, float beamWidth, float beamHeight, uint32_t color, int segments);
    ERS_IMPORT void ERS_Mesh_PushText3DAlignedDefault(void* instance, const char* text, float centerX, float centerY, float centerZ, float normalX, float normalY, float normalZ, float worldUpx, float worldUpy, float worldUpz, float scale, uint32_t color);
    ERS_IMPORT void ERS_Mesh_PushTextBillboardDefault(void* instance, const char* text, float posX, float posY, float posZ, float cameraX, float cameraY, float cameraZ, float worldUpx, float worldUpy, float worldUpz, float scale, uint32_t color);
    ERS_IMPORT bool ERS_Mesh_CreateBuffers(void* instance);
    ERS_IMPORT void ERS_Mesh_DeleteBuffers(void* instance);
    ERS_IMPORT void ERS_Mesh_UpdateBuffers(void* instance);
    ERS_IMPORT void ERS_Mesh_Draw(void* instance, void* shaderInstance);
    ERS_IMPORT size_t ERS_Mesh_GetVertexCount(void* instance);
    ERS_IMPORT size_t ERS_Mesh_GetIndexCount(void* instance);
    ERS_IMPORT bool ERS_Mesh_HasBuffers(void* instance);
    ERS_IMPORT uint32_t ERS_Mesh_GetVAO(void* instance);
    ERS_IMPORT void ERS_Mesh_TransformVertices2(void* instance, float translationX, float translationY, float translationZ, float axisX, float axisY, float axisZ, float turns, float scaleX, float scaleY, float scaleZ);
    ERS_IMPORT void ERS_Mesh_TransformVertices(void* instance, float* transform16);
    ERS_IMPORT void ERS_Mesh_TransformVerticesRange(void* instance, float* transform16, uint32_t startIdx, uint32_t endIdx);
    ERS_IMPORT void ERS_Mesh_CenterAtOrigin(void* instance);
    ERS_IMPORT void ERS_Mesh_TranslateToFloor(void* instance);
    ERS_IMPORT void ERS_Mesh_SetColor(void* instance, uint32_t color);
    ERS_IMPORT void ERS_Mesh_Normalize(void* instance);
    ERS_IMPORT void ERS_Mesh_GetMax(void* instance, float* outX, float* outY, float* outZ);
    ERS_IMPORT void ERS_Mesh_GetMin(void* instance, float* outX, float* outY, float* outZ);
    ERS_IMPORT void ERS_Mesh_SetTransform(void* instance, float* transform16);
    ERS_IMPORT void ERS_Mesh_PushMesh(void* instance, const void* otherInstance, float posX, float posY, float posZ, float axisX, float axisY, float axisZ, float turns, float scaleX, float scaleY, float scaleZ);
    ERS_IMPORT void ERS_Mesh_GetTransform(void* instance, float* outTransform16);
    ERS_IMPORT void* ERS_Model3D_Create();
    ERS_IMPORT void ERS_Model3D_Destroy(void* model);
    ERS_IMPORT bool ERS_Model3D_Load(void* modelHandle, const char* path);
    ERS_IMPORT uint32_t ERS_Model3D_GetMeshCount(void* modelHandle);
    ERS_IMPORT void ERS_Model3D_SetTransform(void* modelHandle, float x, float y, float z, float xRotAxis, float yRotAxis, float zRotAxis, float turns, float xScale, float yScale, float zScale);
    ERS_IMPORT void ERS_Model3D_GetTransform(void* modelHandle, float* transformOut);
    ERS_IMPORT void* ERS_Model3D_GetMesh(void* modelHandle, int index);
    ERS_IMPORT void* ERS_RenderContext_Create(int screenWidth, int screenHeight);
    ERS_IMPORT void ERS_RenderContext_Destroy(void* instance);
    ERS_IMPORT void* ERS_RenderContext_GetCamera2D(void* instance);
    ERS_IMPORT void ERS_RenderContext_SetViewport(void* instance, int width, int height);
    ERS_IMPORT bool ERS_RenderContext_Get_DrawBackgroundGrid(void* instance);
    ERS_IMPORT void ERS_RenderContext_Set_DrawBackgroundGrid(void* instance, bool value);
    ERS_IMPORT uint32_t ERS_RenderContext_Get_BackgroundColor(void* instance);
    ERS_IMPORT void ERS_RenderContext_Set_BackgroundColor(void* instance, uint32_t color);
    ERS_IMPORT uint32_t ERS_RenderContext_Get_BackgroundGridColor(void* instance);
    ERS_IMPORT void ERS_RenderContext_Set_BackgroundGridColor(void* instance, uint32_t color);
    ERS_IMPORT void* ERS_RenderContext_GetCamera3D(void* instance);
    ERS_IMPORT void ERS_RenderContext_ClearScreen(void* instance);
    ERS_IMPORT void ERS_RenderContext_Begin2D(void* instance);
    ERS_IMPORT void ERS_RenderContext_End2D(void* instance);
    ERS_IMPORT void ERS_RenderContext_Begin3D(void* instance);
    ERS_IMPORT void ERS_RenderContext_End3D(void* instance);
    ERS_IMPORT void ERS_RenderContext_DrawQuad2D(void* instance, float x0, float y0, float x1, float y1, float x2, float y2, float x3, float y3, uint32_t color, int64_t zIndex);
    ERS_IMPORT void ERS_RenderContext_DrawRect2D(void* instance, float x, float y, float sizeX, float sizeY, float angle, uint32_t color, int64_t zIndex);
    ERS_IMPORT void ERS_RenderContext_DrawCircle2D(void* instance, float centerX, float centerY, float sizeX, float sizeY, int segments, float angle, uint32_t color, int64_t zIndex);
    ERS_IMPORT void ERS_RenderContext_DrawScreenLine2D(void* instance, float x0, float y0, float x1, float y1, float thickness, uint32_t color, int64_t zIndex);
    ERS_IMPORT void ERS_RenderContext_DrawScreenLineRect2D(void* instance, float x, float y, float sizeX, float sizeY, float angle, float thickness, uint32_t color, int64_t zIndex);
    ERS_IMPORT void ERS_RenderContext_DrawTextBillboard(void* instance, const char* text, float centerX, float centerY, float centerZ, float scale, uint32_t color);
    ERS_IMPORT void ERS_RenderContext_DrawText2D(void* instance, const char* text, float x, float y, float scale, uint32_t color, int64_t zIndex);
    ERS_IMPORT void ERS_RenderContext_DrawTexture2D(void* instance, void* textureHandle, float x, float y, float width, float height, float uvMinX, float uvMinY, float uvMaxX, float uvMaxY, float angle, uint32_t color, int64_t zIndex);
    ERS_IMPORT void ERS_RenderContext_DrawCube3D(void* instance, float x, float y, float z, float xRotation, float yRotation, float zRotation, float xScale, float yScale, float zScale, uint32_t color);
    ERS_IMPORT void ERS_RenderContext_DrawText3D(void* instance, const char* text, float centerX, float centerY, float centerZ, float normalX, float normalY, float normalZ, float worldUpX, float worldUpY, float worldUpZ, float scale, uint32_t color);
    ERS_IMPORT void ERS_RenderContext_SetLightDirection(void* instance, float x, float y, float z);
    ERS_IMPORT void ERS_RenderContext_DrawLine2D(void* instance, float x0, float y0, float x1, float y1, float thickness, uint32_t color, int64_t zIndex);
    ERS_IMPORT void ERS_RenderContext_DrawTriangle2D(void* instance, float x0, float y0, float x1, float y1, float x2, float y2, uint32_t color, int64_t zIndex);
    ERS_IMPORT void ERS_RenderContext_DrawTriangle2D_Box(void* instance, float centerX, float centerY, float sizeX, float sizeY, float angle, uint32_t color, int64_t zIndex);
    ERS_IMPORT void ERS_RenderContext_DrawInstancedModel3DWithMesh(void* renderContextHandle, void* meshHandle, void* instancedModelHandle);
    ERS_IMPORT void ERS_RenderContext_DrawInstancedModel3D(void* renderContextHandle, void* instancedModelHandle);
    ERS_IMPORT void ERS_RenderContext_DrawArc2D(void* renderContextHandle, float centerX, float centerY, float radius, float width, float beginAngle, float endAngle, int segments, uint32_t color, int64_t zIndex);
    ERS_IMPORT void ERS_RenderContext_DrawModel3D(void* instanceHandle, void* modelHandle);
    ERS_IMPORT void ERS_RenderContext_DrawMesh(void* instance, void* meshHandle);
    ERS_IMPORT void ERS_RenderContext_CalculateTextSize(void* instance, const char* text, float scale, float* width, float* height);
    ERS_IMPORT bool ERS_RenderContext_IsOpenGLInitialized();
    ERS_IMPORT bool ERS_RenderContext_InitializeOpenGL(void* windowHandle, void* displayHandle);
    ERS_IMPORT void* ERS_RenderFramework_Create(void* windowHandle, void* displayHandle, int screenWidth, int screenHeight);
    ERS_IMPORT void ERS_RenderFramework_Present(void* instance);
    ERS_IMPORT void ERS_RenderFramework_DrawRenderContext(void* instance, void* renderContextHandle);
    ERS_IMPORT void ERS_RenderFramework_Destroy(void* instance);
    ERS_IMPORT void* ERS_Texture_Create();
    ERS_IMPORT void ERS_Texture_Load(void* instance, const char* path);
    ERS_IMPORT void ERS_Texture_Release(void* instance);
}
#endif // ERS_API_FUNCTIONS_IMPLEMENTATION

